apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techwave-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/luismuma/techwave_web_K8s.git
    targetRevision: main
    path: helm/flask-app   # ✅ IMPORTANTE
    helm:
      valueFiles:
        - values-green.yaml   # ✅ para tu pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      
