apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techwave-web
  namespace: argocd   # 👈 donde vive Argo CD
spec:
  project: default
  source:
    repoURL: https://github.com/luismuma/techwave_web_K8s.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app   # 👈 donde se despliega tu app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
