# argocd-application-controller-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller-rbac  # Apunta al ClusterRole 
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd
